//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace SharedLibs.Chester {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Net;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonSoap", Namespace="http://tempuri.org/")]
    public partial class Common : System.Web.Services.Protocols.SoapHttpClientProtocol {

        public String Cookies { get; set; }

        protected override WebRequest GetWebRequest(Uri uri) {

            WebRequest request = base.GetWebRequest(uri);
            request.Headers["Cookie"] = this.Cookies;
            return request;
        }

        protected override WebResponse GetWebResponse(WebRequest request) {

            WebResponse response = base.GetWebResponse(request);
            return response;
        }
        
        private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateProductNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCustomerAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCustomerContactPersonOperationCompleted;
        
        /// <remarks/>
        public Common() {
            this.Url = "http://chester-stage-tr.havit.eu/WebServices/Common.asmx";
        }

        public Common(String endpoint) {
            this.Url = endpoint;
        }
        
        /// <remarks/>
        public event GetCustomersCompletedEventHandler GetCustomersCompleted;
        
        /// <remarks/>
        public event ValidateProductNumberCompletedEventHandler ValidateProductNumberCompleted;
        
        /// <remarks/>
        public event CreateCustomerAddressCompletedEventHandler CreateCustomerAddressCompleted;
        
        /// <remarks/>
        public event CreateCustomerContactPersonCompletedEventHandler CreateCustomerContactPersonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerWso[] GetCustomers(string customerNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> customerID, string customerName, string ic) {
            object[] results = this.Invoke("GetCustomers", new object[] {
                        customerNumber,
                        customerID,
                        customerName,
                        ic});
            return ((CustomerWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomers(string customerNumber, System.Nullable<int> customerID, string customerName, string ic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomers", new object[] {
                        customerNumber,
                        customerID,
                        customerName,
                        ic}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerWso[] EndGetCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersAsync(string customerNumber, System.Nullable<int> customerID, string customerName, string ic) {
            this.GetCustomersAsync(customerNumber, customerID, customerName, ic, null);
        }
        
        /// <remarks/>
        public void GetCustomersAsync(string customerNumber, System.Nullable<int> customerID, string customerName, string ic, object userState) {
            if ((this.GetCustomersOperationCompleted == null)) {
                this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
            }
            this.InvokeAsync("GetCustomers", new object[] {
                        customerNumber,
                        customerID,
                        customerName,
                        ic}, this.GetCustomersOperationCompleted, userState);
        }
        
        private void OnGetCustomersOperationCompleted(object arg) {
            if ((this.GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateProductNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductNumberValidationWso ValidateProductNumber(string productNumberBatch) {
            object[] results = this.Invoke("ValidateProductNumber", new object[] {
                        productNumberBatch});
            return ((ProductNumberValidationWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateProductNumber(string productNumberBatch, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateProductNumber", new object[] {
                        productNumberBatch}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductNumberValidationWso EndValidateProductNumber(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProductNumberValidationWso)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateProductNumberAsync(string productNumberBatch) {
            this.ValidateProductNumberAsync(productNumberBatch, null);
        }
        
        /// <remarks/>
        public void ValidateProductNumberAsync(string productNumberBatch, object userState) {
            if ((this.ValidateProductNumberOperationCompleted == null)) {
                this.ValidateProductNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateProductNumberOperationCompleted);
            }
            this.InvokeAsync("ValidateProductNumber", new object[] {
                        productNumberBatch}, this.ValidateProductNumberOperationCompleted, userState);
        }
        
        private void OnValidateProductNumberOperationCompleted(object arg) {
            if ((this.ValidateProductNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateProductNumberCompleted(this, new ValidateProductNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCustomerAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreatedCustomerAddressWso CreateCustomerAddress(string customerNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> customerID, string name, string street, string city, string zipCode, string country, string buildingCode, string floor, string roomNumber) {
            object[] results = this.Invoke("CreateCustomerAddress", new object[] {
                        customerNumber,
                        customerID,
                        name,
                        street,
                        city,
                        zipCode,
                        country,
                        buildingCode,
                        floor,
                        roomNumber});
            return ((CreatedCustomerAddressWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateCustomerAddress(string customerNumber, System.Nullable<int> customerID, string name, string street, string city, string zipCode, string country, string buildingCode, string floor, string roomNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateCustomerAddress", new object[] {
                        customerNumber,
                        customerID,
                        name,
                        street,
                        city,
                        zipCode,
                        country,
                        buildingCode,
                        floor,
                        roomNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public CreatedCustomerAddressWso EndCreateCustomerAddress(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreatedCustomerAddressWso)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCustomerAddressAsync(string customerNumber, System.Nullable<int> customerID, string name, string street, string city, string zipCode, string country, string buildingCode, string floor, string roomNumber) {
            this.CreateCustomerAddressAsync(customerNumber, customerID, name, street, city, zipCode, country, buildingCode, floor, roomNumber, null);
        }
        
        /// <remarks/>
        public void CreateCustomerAddressAsync(string customerNumber, System.Nullable<int> customerID, string name, string street, string city, string zipCode, string country, string buildingCode, string floor, string roomNumber, object userState) {
            if ((this.CreateCustomerAddressOperationCompleted == null)) {
                this.CreateCustomerAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCustomerAddressOperationCompleted);
            }
            this.InvokeAsync("CreateCustomerAddress", new object[] {
                        customerNumber,
                        customerID,
                        name,
                        street,
                        city,
                        zipCode,
                        country,
                        buildingCode,
                        floor,
                        roomNumber}, this.CreateCustomerAddressOperationCompleted, userState);
        }
        
        private void OnCreateCustomerAddressOperationCompleted(object arg) {
            if ((this.CreateCustomerAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCustomerAddressCompleted(this, new CreateCustomerAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCustomerContactPerson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreatedCustomerContactPersonWso CreateCustomerContactPerson(string customerNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> customerID, string name, string email, string phone) {
            object[] results = this.Invoke("CreateCustomerContactPerson", new object[] {
                        customerNumber,
                        customerID,
                        name,
                        email,
                        phone});
            return ((CreatedCustomerContactPersonWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateCustomerContactPerson(string customerNumber, System.Nullable<int> customerID, string name, string email, string phone, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateCustomerContactPerson", new object[] {
                        customerNumber,
                        customerID,
                        name,
                        email,
                        phone}, callback, asyncState);
        }
        
        /// <remarks/>
        public CreatedCustomerContactPersonWso EndCreateCustomerContactPerson(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreatedCustomerContactPersonWso)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCustomerContactPersonAsync(string customerNumber, System.Nullable<int> customerID, string name, string email, string phone) {
            this.CreateCustomerContactPersonAsync(customerNumber, customerID, name, email, phone, null);
        }
        
        /// <remarks/>
        public void CreateCustomerContactPersonAsync(string customerNumber, System.Nullable<int> customerID, string name, string email, string phone, object userState) {
            if ((this.CreateCustomerContactPersonOperationCompleted == null)) {
                this.CreateCustomerContactPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCustomerContactPersonOperationCompleted);
            }
            this.InvokeAsync("CreateCustomerContactPerson", new object[] {
                        customerNumber,
                        customerID,
                        name,
                        email,
                        phone}, this.CreateCustomerContactPersonOperationCompleted, userState);
        }
        
        private void OnCreateCustomerContactPersonOperationCompleted(object arg) {
            if ((this.CreateCustomerContactPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCustomerContactPersonCompleted(this, new CreateCustomerContactPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerWso {
        
        private int customerIDField;
        
        private string customerNumberField;
        
        private string customerNameField;
        
        private string icField;
        
        private AddressWso[] addressesField;
        
        private ContactPersonWso[] contactPersonsField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Ic {
            get {
                return this.icField;
            }
            set {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        public AddressWso[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public ContactPersonWso[] ContactPersons {
            get {
                return this.contactPersonsField;
            }
            set {
                this.contactPersonsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddressWso {
        
        private int addressIDField;
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string countryField;
        
        private string buildingCodeField;
        
        private string floorField;
        
        private string roomNumberField;
        
        /// <remarks/>
        public int AddressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingCode {
            get {
                return this.buildingCodeField;
            }
            set {
                this.buildingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        public string RoomNumber {
            get {
                return this.roomNumberField;
            }
            set {
                this.roomNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatedCustomerContactPersonWso {
        
        private int contactPersonIDField;
        
        /// <remarks/>
        public int ContactPersonID {
            get {
                return this.contactPersonIDField;
            }
            set {
                this.contactPersonIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatedCustomerAddressWso {
        
        private int addressIDField;
        
        /// <remarks/>
        public int AddressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductNumberValidationWso {
        
        private bool numberIsValidField;
        
        private string materialNameField;
        
        private string equipmentModelField;
        
        /// <remarks/>
        public bool NumberIsValid {
            get {
                return this.numberIsValidField;
            }
            set {
                this.numberIsValidField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        public string EquipmentModel {
            get {
                return this.equipmentModelField;
            }
            set {
                this.equipmentModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactPersonWso {
        
        private int contactPersonIDField;
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        /// <remarks/>
        public int ContactPersonID {
            get {
                return this.contactPersonIDField;
            }
            set {
                this.contactPersonIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerWso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void ValidateProductNumberCompletedEventHandler(object sender, ValidateProductNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateProductNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateProductNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductNumberValidationWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductNumberValidationWso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CreateCustomerAddressCompletedEventHandler(object sender, CreateCustomerAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCustomerAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCustomerAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreatedCustomerAddressWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreatedCustomerAddressWso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CreateCustomerContactPersonCompletedEventHandler(object sender, CreateCustomerContactPersonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCustomerContactPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCustomerContactPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreatedCustomerContactPersonWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreatedCustomerContactPersonWso)(this.results[0]));
            }
        }
    }
}
