//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace SharedLibs.Chester {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Net;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CounterWso))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachmentWsoBase))]
    public partial class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {

        public String Cookies { get; set; }

        protected override WebRequest GetWebRequest(Uri uri) {

            WebRequest request = base.GetWebRequest(uri);
            request.Headers["Cookie"] = this.Cookies;
            return request;
        }

        protected override WebResponse GetWebResponse(WebRequest request) {

            WebResponse response = base.GetWebResponse(request);
            return response;
        }
        
        private System.Threading.SendOrPostCallback GetServiceCallsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateServiceCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCounterValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCounterCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEquipmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumablesOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsumablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateConsumablesOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceDatesOperationCompleted;
        
        /// <remarks/>
        public CustomerService() {
            this.Url = "http://chester-stage-tr.havit.eu/WebServices/CustomerService.asmx";
        }

        public CustomerService(String endpoint) {
            this.Url = endpoint;
        }
        
        /// <remarks/>
        public event GetServiceCallsCompletedEventHandler GetServiceCallsCompleted;
        
        /// <remarks/>
        public event CreateServiceCallCompletedEventHandler CreateServiceCallCompleted;
        
        /// <remarks/>
        public event GetCounterValuesCompletedEventHandler GetCounterValuesCompleted;
        
        /// <remarks/>
        public event CreateCounterCardCompletedEventHandler CreateCounterCardCompleted;
        
        /// <remarks/>
        public event GetEquipmentsCompletedEventHandler GetEquipmentsCompleted;
        
        /// <remarks/>
        public event GetCustomerCompletedEventHandler GetCustomerCompleted;
        
        /// <remarks/>
        public event GetConsumablesOrdersCompletedEventHandler GetConsumablesOrdersCompleted;
        
        /// <remarks/>
        public event GetConsumablesCompletedEventHandler GetConsumablesCompleted;
        
        /// <remarks/>
        public event CreateConsumablesOrderCompletedEventHandler CreateConsumablesOrderCompleted;
        
        /// <remarks/>
        public event GetInvoiceDatesCompletedEventHandler GetInvoiceDatesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServiceCalls", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceCallWso[] GetServiceCalls([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> serviceCallID, string notificationNumber, string serviceOrderNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> stateID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> isClosed, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> reportedFrom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> reportedTo) {
            object[] results = this.Invoke("GetServiceCalls", new object[] {
                        serviceCallID,
                        notificationNumber,
                        serviceOrderNumber,
                        equipmentID,
                        equipmentSerialNumber,
                        stateID,
                        isClosed,
                        reportedFrom,
                        reportedTo});
            return ((ServiceCallWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetServiceCalls(System.Nullable<int> serviceCallID, string notificationNumber, string serviceOrderNumber, System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<int> stateID, System.Nullable<bool> isClosed, System.Nullable<System.DateTime> reportedFrom, System.Nullable<System.DateTime> reportedTo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetServiceCalls", new object[] {
                        serviceCallID,
                        notificationNumber,
                        serviceOrderNumber,
                        equipmentID,
                        equipmentSerialNumber,
                        stateID,
                        isClosed,
                        reportedFrom,
                        reportedTo}, callback, asyncState);
        }
        
        /// <remarks/>
        public ServiceCallWso[] EndGetServiceCalls(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ServiceCallWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceCallsAsync(System.Nullable<int> serviceCallID, string notificationNumber, string serviceOrderNumber, System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<int> stateID, System.Nullable<bool> isClosed, System.Nullable<System.DateTime> reportedFrom, System.Nullable<System.DateTime> reportedTo) {
            this.GetServiceCallsAsync(serviceCallID, notificationNumber, serviceOrderNumber, equipmentID, equipmentSerialNumber, stateID, isClosed, reportedFrom, reportedTo, null);
        }
        
        /// <remarks/>
        public void GetServiceCallsAsync(System.Nullable<int> serviceCallID, string notificationNumber, string serviceOrderNumber, System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<int> stateID, System.Nullable<bool> isClosed, System.Nullable<System.DateTime> reportedFrom, System.Nullable<System.DateTime> reportedTo, object userState) {
            if ((this.GetServiceCallsOperationCompleted == null)) {
                this.GetServiceCallsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceCallsOperationCompleted);
            }
            this.InvokeAsync("GetServiceCalls", new object[] {
                        serviceCallID,
                        notificationNumber,
                        serviceOrderNumber,
                        equipmentID,
                        equipmentSerialNumber,
                        stateID,
                        isClosed,
                        reportedFrom,
                        reportedTo}, this.GetServiceCallsOperationCompleted, userState);
        }
        
        private void OnGetServiceCallsOperationCompleted(object arg) {
            if ((this.GetServiceCallsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceCallsCompleted(this, new GetServiceCallsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateServiceCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreatedServiceCallWso CreateServiceCall([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber, string title, string description, int callTypeID, string customerReference, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> addressID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> contactPersonID) {
            object[] results = this.Invoke("CreateServiceCall", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        title,
                        description,
                        callTypeID,
                        customerReference,
                        addressID,
                        contactPersonID});
            return ((CreatedServiceCallWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateServiceCall(System.Nullable<int> equipmentID, string equipmentSerialNumber, string title, string description, int callTypeID, string customerReference, System.Nullable<int> addressID, System.Nullable<int> contactPersonID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateServiceCall", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        title,
                        description,
                        callTypeID,
                        customerReference,
                        addressID,
                        contactPersonID}, callback, asyncState);
        }
        
        /// <remarks/>
        public CreatedServiceCallWso EndCreateServiceCall(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreatedServiceCallWso)(results[0]));
        }
        
        /// <remarks/>
        public void CreateServiceCallAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, string title, string description, int callTypeID, string customerReference, System.Nullable<int> addressID, System.Nullable<int> contactPersonID) {
            this.CreateServiceCallAsync(equipmentID, equipmentSerialNumber, title, description, callTypeID, customerReference, addressID, contactPersonID, null);
        }
        
        /// <remarks/>
        public void CreateServiceCallAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, string title, string description, int callTypeID, string customerReference, System.Nullable<int> addressID, System.Nullable<int> contactPersonID, object userState) {
            if ((this.CreateServiceCallOperationCompleted == null)) {
                this.CreateServiceCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateServiceCallOperationCompleted);
            }
            this.InvokeAsync("CreateServiceCall", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        title,
                        description,
                        callTypeID,
                        customerReference,
                        addressID,
                        contactPersonID}, this.CreateServiceCallOperationCompleted, userState);
        }
        
        private void OnCreateServiceCallOperationCompleted(object arg) {
            if ((this.CreateServiceCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateServiceCallCompleted(this, new CreateServiceCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCounterValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CounterHistoryWso[] GetCounterValues([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber, System.DateTime fromDate, System.DateTime toDate) {
            object[] results = this.Invoke("GetCounterValues", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        fromDate,
                        toDate});
            return ((CounterHistoryWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCounterValues(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.DateTime fromDate, System.DateTime toDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCounterValues", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        fromDate,
                        toDate}, callback, asyncState);
        }
        
        /// <remarks/>
        public CounterHistoryWso[] EndGetCounterValues(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CounterHistoryWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCounterValuesAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.DateTime fromDate, System.DateTime toDate) {
            this.GetCounterValuesAsync(equipmentID, equipmentSerialNumber, fromDate, toDate, null);
        }
        
        /// <remarks/>
        public void GetCounterValuesAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.DateTime fromDate, System.DateTime toDate, object userState) {
            if ((this.GetCounterValuesOperationCompleted == null)) {
                this.GetCounterValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCounterValuesOperationCompleted);
            }
            this.InvokeAsync("GetCounterValues", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        fromDate,
                        toDate}, this.GetCounterValuesOperationCompleted, userState);
        }
        
        private void OnGetCounterValuesOperationCompleted(object arg) {
            if ((this.GetCounterValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCounterValuesCompleted(this, new GetCounterValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCounterCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreatedCounterCardWso CreateCounterCard([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber, CounterValueWso[] counterValues) {
            object[] results = this.Invoke("CreateCounterCard", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        counterValues});
            return ((CreatedCounterCardWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateCounterCard(System.Nullable<int> equipmentID, string equipmentSerialNumber, CounterValueWso[] counterValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateCounterCard", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        counterValues}, callback, asyncState);
        }
        
        /// <remarks/>
        public CreatedCounterCardWso EndCreateCounterCard(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreatedCounterCardWso)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCounterCardAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, CounterValueWso[] counterValues) {
            this.CreateCounterCardAsync(equipmentID, equipmentSerialNumber, counterValues, null);
        }
        
        /// <remarks/>
        public void CreateCounterCardAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, CounterValueWso[] counterValues, object userState) {
            if ((this.CreateCounterCardOperationCompleted == null)) {
                this.CreateCounterCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCounterCardOperationCompleted);
            }
            this.InvokeAsync("CreateCounterCard", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        counterValues}, this.CreateCounterCardOperationCompleted, userState);
        }
        
        private void OnCreateCounterCardOperationCompleted(object arg) {
            if ((this.CreateCounterCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCounterCardCompleted(this, new CreateCounterCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEquipments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EquipmentWso[] GetEquipments([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string serialNumber) {
            object[] results = this.Invoke("GetEquipments", new object[] {
                        equipmentID,
                        serialNumber});
            return ((EquipmentWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEquipments(System.Nullable<int> equipmentID, string serialNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEquipments", new object[] {
                        equipmentID,
                        serialNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public EquipmentWso[] EndGetEquipments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EquipmentWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEquipmentsAsync(System.Nullable<int> equipmentID, string serialNumber) {
            this.GetEquipmentsAsync(equipmentID, serialNumber, null);
        }
        
        /// <remarks/>
        public void GetEquipmentsAsync(System.Nullable<int> equipmentID, string serialNumber, object userState) {
            if ((this.GetEquipmentsOperationCompleted == null)) {
                this.GetEquipmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEquipmentsOperationCompleted);
            }
            this.InvokeAsync("GetEquipments", new object[] {
                        equipmentID,
                        serialNumber}, this.GetEquipmentsOperationCompleted, userState);
        }
        
        private void OnGetEquipmentsOperationCompleted(object arg) {
            if ((this.GetEquipmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEquipmentsCompleted(this, new GetEquipmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerWso GetCustomer() {
            object[] results = this.Invoke("GetCustomer", new object[0]);
            return ((CustomerWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomer(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomer", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerWso EndGetCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerWso)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerAsync() {
            this.GetCustomerAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerAsync(object userState) {
            if ((this.GetCustomerOperationCompleted == null)) {
                this.GetCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerOperationCompleted);
            }
            this.InvokeAsync("GetCustomer", new object[0], this.GetCustomerOperationCompleted, userState);
        }
        
        private void OnGetCustomerOperationCompleted(object arg) {
            if ((this.GetCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerCompleted(this, new GetCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumablesOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsumablesOrderWso[] GetConsumablesOrders([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> consumablesOrderID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> stateID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> orderedFrom, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> orderedTo) {
            object[] results = this.Invoke("GetConsumablesOrders", new object[] {
                        consumablesOrderID,
                        equipmentID,
                        equipmentSerialNumber,
                        stateID,
                        orderedFrom,
                        orderedTo});
            return ((ConsumablesOrderWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetConsumablesOrders(System.Nullable<int> consumablesOrderID, System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<int> stateID, System.Nullable<System.DateTime> orderedFrom, System.Nullable<System.DateTime> orderedTo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetConsumablesOrders", new object[] {
                        consumablesOrderID,
                        equipmentID,
                        equipmentSerialNumber,
                        stateID,
                        orderedFrom,
                        orderedTo}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsumablesOrderWso[] EndGetConsumablesOrders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsumablesOrderWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumablesOrdersAsync(System.Nullable<int> consumablesOrderID, System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<int> stateID, System.Nullable<System.DateTime> orderedFrom, System.Nullable<System.DateTime> orderedTo) {
            this.GetConsumablesOrdersAsync(consumablesOrderID, equipmentID, equipmentSerialNumber, stateID, orderedFrom, orderedTo, null);
        }
        
        /// <remarks/>
        public void GetConsumablesOrdersAsync(System.Nullable<int> consumablesOrderID, System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<int> stateID, System.Nullable<System.DateTime> orderedFrom, System.Nullable<System.DateTime> orderedTo, object userState) {
            if ((this.GetConsumablesOrdersOperationCompleted == null)) {
                this.GetConsumablesOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumablesOrdersOperationCompleted);
            }
            this.InvokeAsync("GetConsumablesOrders", new object[] {
                        consumablesOrderID,
                        equipmentID,
                        equipmentSerialNumber,
                        stateID,
                        orderedFrom,
                        orderedTo}, this.GetConsumablesOrdersOperationCompleted, userState);
        }
        
        private void OnGetConsumablesOrdersOperationCompleted(object arg) {
            if ((this.GetConsumablesOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumablesOrdersCompleted(this, new GetConsumablesOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConsumables", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MaterialWso[] GetConsumables([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber) {
            object[] results = this.Invoke("GetConsumables", new object[] {
                        equipmentID,
                        equipmentSerialNumber});
            return ((MaterialWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetConsumables(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetConsumables", new object[] {
                        equipmentID,
                        equipmentSerialNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public MaterialWso[] EndGetConsumables(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MaterialWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConsumablesAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber) {
            this.GetConsumablesAsync(equipmentID, equipmentSerialNumber, null);
        }
        
        /// <remarks/>
        public void GetConsumablesAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, object userState) {
            if ((this.GetConsumablesOperationCompleted == null)) {
                this.GetConsumablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsumablesOperationCompleted);
            }
            this.InvokeAsync("GetConsumables", new object[] {
                        equipmentID,
                        equipmentSerialNumber}, this.GetConsumablesOperationCompleted, userState);
        }
        
        private void OnGetConsumablesOperationCompleted(object arg) {
            if ((this.GetConsumablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsumablesCompleted(this, new GetConsumablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateConsumablesOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConsumablesOrderWso CreateConsumablesOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> equipmentID, string equipmentSerialNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> requestedDeliveryDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> deliveryAddressID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> contactPersonID, string messageForCarrier, string noteForXerox, ConsumablesOrderMaterialOrdered[] orderedItems, bool returnUsedSupplies, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> packageCount, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> palletCount) {
            object[] results = this.Invoke("CreateConsumablesOrder", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        requestedDeliveryDate,
                        deliveryAddressID,
                        contactPersonID,
                        messageForCarrier,
                        noteForXerox,
                        orderedItems,
                        returnUsedSupplies,
                        packageCount,
                        palletCount});
            return ((ConsumablesOrderWso)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateConsumablesOrder(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<System.DateTime> requestedDeliveryDate, System.Nullable<int> deliveryAddressID, System.Nullable<int> contactPersonID, string messageForCarrier, string noteForXerox, ConsumablesOrderMaterialOrdered[] orderedItems, bool returnUsedSupplies, System.Nullable<int> packageCount, System.Nullable<int> palletCount, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateConsumablesOrder", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        requestedDeliveryDate,
                        deliveryAddressID,
                        contactPersonID,
                        messageForCarrier,
                        noteForXerox,
                        orderedItems,
                        returnUsedSupplies,
                        packageCount,
                        palletCount}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsumablesOrderWso EndCreateConsumablesOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsumablesOrderWso)(results[0]));
        }
        
        /// <remarks/>
        public void CreateConsumablesOrderAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<System.DateTime> requestedDeliveryDate, System.Nullable<int> deliveryAddressID, System.Nullable<int> contactPersonID, string messageForCarrier, string noteForXerox, ConsumablesOrderMaterialOrdered[] orderedItems, bool returnUsedSupplies, System.Nullable<int> packageCount, System.Nullable<int> palletCount) {
            this.CreateConsumablesOrderAsync(equipmentID, equipmentSerialNumber, requestedDeliveryDate, deliveryAddressID, contactPersonID, messageForCarrier, noteForXerox, orderedItems, returnUsedSupplies, packageCount, palletCount, null);
        }
        
        /// <remarks/>
        public void CreateConsumablesOrderAsync(System.Nullable<int> equipmentID, string equipmentSerialNumber, System.Nullable<System.DateTime> requestedDeliveryDate, System.Nullable<int> deliveryAddressID, System.Nullable<int> contactPersonID, string messageForCarrier, string noteForXerox, ConsumablesOrderMaterialOrdered[] orderedItems, bool returnUsedSupplies, System.Nullable<int> packageCount, System.Nullable<int> palletCount, object userState) {
            if ((this.CreateConsumablesOrderOperationCompleted == null)) {
                this.CreateConsumablesOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateConsumablesOrderOperationCompleted);
            }
            this.InvokeAsync("CreateConsumablesOrder", new object[] {
                        equipmentID,
                        equipmentSerialNumber,
                        requestedDeliveryDate,
                        deliveryAddressID,
                        contactPersonID,
                        messageForCarrier,
                        noteForXerox,
                        orderedItems,
                        returnUsedSupplies,
                        packageCount,
                        palletCount}, this.CreateConsumablesOrderOperationCompleted, userState);
        }
        
        private void OnCreateConsumablesOrderOperationCompleted(object arg) {
            if ((this.CreateConsumablesOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateConsumablesOrderCompleted(this, new CreateConsumablesOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoiceDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvoiceDateWso[] GetInvoiceDates() {
            object[] results = this.Invoke("GetInvoiceDates", new object[0]);
            return ((InvoiceDateWso[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoiceDates(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoiceDates", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public InvoiceDateWso[] EndGetInvoiceDates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InvoiceDateWso[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceDatesAsync() {
            this.GetInvoiceDatesAsync(null);
        }
        
        /// <remarks/>
        public void GetInvoiceDatesAsync(object userState) {
            if ((this.GetInvoiceDatesOperationCompleted == null)) {
                this.GetInvoiceDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceDatesOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceDates", new object[0], this.GetInvoiceDatesOperationCompleted, userState);
        }
        
        private void OnGetInvoiceDatesOperationCompleted(object arg) {
            if ((this.GetInvoiceDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceDatesCompleted(this, new GetInvoiceDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceCallWso {
        
        private int serviceCallIDField;
        
        private int customerIDField;
        
        private string notificationNumberField;
        
        private string equipmentSerialNumberField;
        
        private string serviceOrderNumberField;
        
        private string equipmentLocationField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int callTypeIDField;
        
        private string customerReferenceField;
        
        private string contactField;
        
        private int stateIDField;
        
        private int brokenCallReasonIDField;
        
        private System.DateTime reportedField;
        
        private PartOrderedWso[] partsOrderedField;
        
        private PartIssuedWso[] partsIssuedField;
        
        private AttachmentWso[] attachmentsField;
        
        /// <remarks/>
        public int ServiceCallID {
            get {
                return this.serviceCallIDField;
            }
            set {
                this.serviceCallIDField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string NotificationNumber {
            get {
                return this.notificationNumberField;
            }
            set {
                this.notificationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EquipmentSerialNumber {
            get {
                return this.equipmentSerialNumberField;
            }
            set {
                this.equipmentSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceOrderNumber {
            get {
                return this.serviceOrderNumberField;
            }
            set {
                this.serviceOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EquipmentLocation {
            get {
                return this.equipmentLocationField;
            }
            set {
                this.equipmentLocationField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int CallTypeID {
            get {
                return this.callTypeIDField;
            }
            set {
                this.callTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public int StateID {
            get {
                return this.stateIDField;
            }
            set {
                this.stateIDField = value;
            }
        }
        
        /// <remarks/>
        public int BrokenCallReasonID {
            get {
                return this.brokenCallReasonIDField;
            }
            set {
                this.brokenCallReasonIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Reported {
            get {
                return this.reportedField;
            }
            set {
                this.reportedField = value;
            }
        }
        
        /// <remarks/>
        public PartOrderedWso[] PartsOrdered {
            get {
                return this.partsOrderedField;
            }
            set {
                this.partsOrderedField = value;
            }
        }
        
        /// <remarks/>
        public PartIssuedWso[] PartsIssued {
            get {
                return this.partsIssuedField;
            }
            set {
                this.partsIssuedField = value;
            }
        }
        
        /// <remarks/>
        public AttachmentWso[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PartOrderedWso {
        
        private System.DateTime orderDateTimeField;
        
        private string materialProductNumberField;
        
        private string productNumberBatchField;
        
        private string nameField;
        
        private decimal quantityField;
        
        /// <remarks/>
        public System.DateTime OrderDateTime {
            get {
                return this.orderDateTimeField;
            }
            set {
                this.orderDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialProductNumber {
            get {
                return this.materialProductNumberField;
            }
            set {
                this.materialProductNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumberBatch {
            get {
                return this.productNumberBatchField;
            }
            set {
                this.productNumberBatchField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EquipmentIdentificationWso {
        
        private int equipmentIDField;
        
        private string serialNumberField;
        
        /// <remarks/>
        public int EquipmentID {
            get {
                return this.equipmentIDField;
            }
            set {
                this.equipmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoiceDateWso {
        
        private System.DateTime dateField;
        
        private EquipmentIdentificationWso[] equipmentsField;
        
        private bool isActiveField;
        
        private System.DateTime activeFromField;
        
        private System.DateTime activeToField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public EquipmentIdentificationWso[] Equipments {
            get {
                return this.equipmentsField;
            }
            set {
                this.equipmentsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActiveFrom {
            get {
                return this.activeFromField;
            }
            set {
                this.activeFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActiveTo {
            get {
                return this.activeToField;
            }
            set {
                this.activeToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumablesOrderMaterialOrdered {
        
        private string productNumberField;
        
        private int quantityField;
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MaterialWso {
        
        private int materialIDField;
        
        private string productNumberField;
        
        private string nameField;
        
        /// <remarks/>
        public int MaterialID {
            get {
                return this.materialIDField;
            }
            set {
                this.materialIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumablesOrderItemWso {
        
        private string materialProductNumberField;
        
        private string materialNameField;
        
        private decimal quantityField;
        
        private System.Nullable<decimal> confirmedQuantityField;
        
        private int stateIDField;
        
        /// <remarks/>
        public string MaterialProductNumber {
            get {
                return this.materialProductNumberField;
            }
            set {
                this.materialProductNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialName {
            get {
                return this.materialNameField;
            }
            set {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ConfirmedQuantity {
            get {
                return this.confirmedQuantityField;
            }
            set {
                this.confirmedQuantityField = value;
            }
        }
        
        /// <remarks/>
        public int StateID {
            get {
                return this.stateIDField;
            }
            set {
                this.stateIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumablesOrderWso {
        
        private int consumablesOrderIDField;
        
        private string numberField;
        
        private int equipmentIDField;
        
        private string equipmentSerialNumberField;
        
        private System.Nullable<System.DateTime> requestedDateField;
        
        private int stateIDField;
        
        private string deliveryAddressField;
        
        private string contactField;
        
        private string messageForCarrierField;
        
        private string noteForXeroxField;
        
        private System.DateTime orderDateField;
        
        private string orderedByField;
        
        private ConsumablesOrderItemWso[] itemsField;
        
        /// <remarks/>
        public int ConsumablesOrderID {
            get {
                return this.consumablesOrderIDField;
            }
            set {
                this.consumablesOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public int EquipmentID {
            get {
                return this.equipmentIDField;
            }
            set {
                this.equipmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string EquipmentSerialNumber {
            get {
                return this.equipmentSerialNumberField;
            }
            set {
                this.equipmentSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RequestedDate {
            get {
                return this.requestedDateField;
            }
            set {
                this.requestedDateField = value;
            }
        }
        
        /// <remarks/>
        public int StateID {
            get {
                return this.stateIDField;
            }
            set {
                this.stateIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string MessageForCarrier {
            get {
                return this.messageForCarrierField;
            }
            set {
                this.messageForCarrierField = value;
            }
        }
        
        /// <remarks/>
        public string NoteForXerox {
            get {
                return this.noteForXeroxField;
            }
            set {
                this.noteForXeroxField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderedBy {
            get {
                return this.orderedByField;
            }
            set {
                this.orderedByField = value;
            }
        }
        
        /// <remarks/>
        public ConsumablesOrderItemWso[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class ContactPersonWso {
        
    //    private int contactPersonIDField;
        
    //    private string nameField;
        
    //    private string emailField;
        
    //    private string phoneField;
        
    //    /// <remarks/>
    //    public int ContactPersonID {
    //        get {
    //            return this.contactPersonIDField;
    //        }
    //        set {
    //            this.contactPersonIDField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Name {
    //        get {
    //            return this.nameField;
    //        }
    //        set {
    //            this.nameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Email {
    //        get {
    //            return this.emailField;
    //        }
    //        set {
    //            this.emailField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Phone {
    //        get {
    //            return this.phoneField;
    //        }
    //        set {
    //            this.phoneField = value;
    //        }
    //    }
    //}
    
    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class AddressWso {
        
    //    private int addressIDField;
        
    //    private string nameField;
        
    //    private string streetField;
        
    //    private string cityField;
        
    //    private string zipCodeField;
        
    //    private string countryField;
        
    //    private string buildingCodeField;
        
    //    private string floorField;
        
    //    private string roomNumberField;
        
    //    /// <remarks/>
    //    public int AddressID {
    //        get {
    //            return this.addressIDField;
    //        }
    //        set {
    //            this.addressIDField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Name {
    //        get {
    //            return this.nameField;
    //        }
    //        set {
    //            this.nameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Street {
    //        get {
    //            return this.streetField;
    //        }
    //        set {
    //            this.streetField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string City {
    //        get {
    //            return this.cityField;
    //        }
    //        set {
    //            this.cityField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string ZipCode {
    //        get {
    //            return this.zipCodeField;
    //        }
    //        set {
    //            this.zipCodeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Country {
    //        get {
    //            return this.countryField;
    //        }
    //        set {
    //            this.countryField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string BuildingCode {
    //        get {
    //            return this.buildingCodeField;
    //        }
    //        set {
    //            this.buildingCodeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Floor {
    //        get {
    //            return this.floorField;
    //        }
    //        set {
    //            this.floorField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string RoomNumber {
    //        get {
    //            return this.roomNumberField;
    //        }
    //        set {
    //            this.roomNumberField = value;
    //        }
    //    }
    //}
    
    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class CustomerWso {
        
    //    private int customerIDField;
        
    //    private string customerNumberField;
        
    //    private string customerNameField;
        
    //    private string icField;
        
    //    private AddressWso[] addressesField;
        
    //    private ContactPersonWso[] contactPersonsField;
        
    //    /// <remarks/>
    //    public int CustomerID {
    //        get {
    //            return this.customerIDField;
    //        }
    //        set {
    //            this.customerIDField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string CustomerNumber {
    //        get {
    //            return this.customerNumberField;
    //        }
    //        set {
    //            this.customerNumberField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string CustomerName {
    //        get {
    //            return this.customerNameField;
    //        }
    //        set {
    //            this.customerNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Ic {
    //        get {
    //            return this.icField;
    //        }
    //        set {
    //            this.icField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public AddressWso[] Addresses {
    //        get {
    //            return this.addressesField;
    //        }
    //        set {
    //            this.addressesField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public ContactPersonWso[] ContactPersons {
    //        get {
    //            return this.contactPersonsField;
    //        }
    //        set {
    //            this.contactPersonsField = value;
    //        }
    //    }
    //}
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EquipmentWso {
        
        private int equipmentIDField;
        
        private string serialNumberField;
        
        private string modelField;
        
        private string mainframeField;
        
        private int customerIDField;
        
        private string customerNumberField;
        
        private string customerLabelField;
        
        private string locationField;
        
        private string contactField;
        
        private string contractNumberField;
        
        private int[] countersField;
        
        private int addressIDField;
        
        private int contactPersonIDField;
        
        /// <remarks/>
        public int EquipmentID {
            get {
                return this.equipmentIDField;
            }
            set {
                this.equipmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Mainframe {
            get {
                return this.mainframeField;
            }
            set {
                this.mainframeField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerLabel {
            get {
                return this.customerLabelField;
            }
            set {
                this.customerLabelField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        public int[] Counters {
            get {
                return this.countersField;
            }
            set {
                this.countersField = value;
            }
        }
        
        /// <remarks/>
        public int AddressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
            }
        }
        
        /// <remarks/>
        public int ContactPersonID {
            get {
                return this.contactPersonIDField;
            }
            set {
                this.contactPersonIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatedCounterCardWso {
        
        private int counterCardIDField;
        
        private System.DateTime reportedField;
        
        /// <remarks/>
        public int CounterCardID {
            get {
                return this.counterCardIDField;
            }
            set {
                this.counterCardIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Reported {
            get {
                return this.reportedField;
            }
            set {
                this.reportedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CounterValueWso {
        
        private int counterTypeIDField;
        
        private decimal counterValueField;
        
        /// <remarks/>
        public int CounterTypeID {
            get {
                return this.counterTypeIDField;
            }
            set {
                this.counterTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal CounterValue {
            get {
                return this.counterValueField;
            }
            set {
                this.counterValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CounterHistoryWso))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CounterWso {
        
        private int typeIDField;
        
        private decimal valueField;
        
        private System.DateTime readingDateTimeField;
        
        private int sourceIDField;
        
        /// <remarks/>
        public int TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReadingDateTime {
            get {
                return this.readingDateTimeField;
            }
            set {
                this.readingDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CounterHistoryWso : CounterWso {
        
        private decimal creditCopiesField;
        
        /// <remarks/>
        public decimal CreditCopies {
            get {
                return this.creditCopiesField;
            }
            set {
                this.creditCopiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatedServiceCallWso {
        
        private int serviceCallIDField;
        
        private System.DateTime reportedField;
        
        /// <remarks/>
        public int ServiceCallID {
            get {
                return this.serviceCallIDField;
            }
            set {
                this.serviceCallIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Reported {
            get {
                return this.reportedField;
            }
            set {
                this.reportedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachmentWso))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachmentWsoBase {
        
        private int attachmentIDField;
        
        private string fileNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int AttachmentID {
            get {
                return this.attachmentIDField;
            }
            set {
                this.attachmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachmentWso : AttachmentWsoBase {
        
        private System.Nullable<bool> visibleToCustomerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> VisibleToCustomer {
            get {
                return this.visibleToCustomerField;
            }
            set {
                this.visibleToCustomerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PartIssuedWso {
        
        private System.DateTime issuedDateTimeField;
        
        private string materialProductNumberField;
        
        private string productNumberBatchField;
        
        private string nameField;
        
        private decimal quantityField;
        
        /// <remarks/>
        public System.DateTime IssuedDateTime {
            get {
                return this.issuedDateTimeField;
            }
            set {
                this.issuedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialProductNumber {
            get {
                return this.materialProductNumberField;
            }
            set {
                this.materialProductNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumberBatch {
            get {
                return this.productNumberBatchField;
            }
            set {
                this.productNumberBatchField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetServiceCallsCompletedEventHandler(object sender, GetServiceCallsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceCallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceCallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceCallWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceCallWso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CreateServiceCallCompletedEventHandler(object sender, CreateServiceCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateServiceCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateServiceCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreatedServiceCallWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreatedServiceCallWso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetCounterValuesCompletedEventHandler(object sender, GetCounterValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCounterValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCounterValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CounterHistoryWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CounterHistoryWso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CreateCounterCardCompletedEventHandler(object sender, CreateCounterCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCounterCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCounterCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreatedCounterCardWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreatedCounterCardWso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetEquipmentsCompletedEventHandler(object sender, GetEquipmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEquipmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEquipmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EquipmentWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EquipmentWso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetCustomerCompletedEventHandler(object sender, GetCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerWso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetConsumablesOrdersCompletedEventHandler(object sender, GetConsumablesOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumablesOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumablesOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsumablesOrderWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsumablesOrderWso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetConsumablesCompletedEventHandler(object sender, GetConsumablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsumablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsumablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MaterialWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MaterialWso[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void CreateConsumablesOrderCompletedEventHandler(object sender, CreateConsumablesOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateConsumablesOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateConsumablesOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsumablesOrderWso Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsumablesOrderWso)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void GetInvoiceDatesCompletedEventHandler(object sender, GetInvoiceDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvoiceDateWso[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoiceDateWso[])(this.results[0]));
            }
        }
    }
}
