//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace SharedLibs.Migros {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateMgrsCallOperationCompleted;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://195.87.99.86/SMSaralUpdateCall/Service.asmx";
        }

        public Service(String endpoint) {
            this.Url = endpoint;
        }
        
        /// <remarks/>
        public event UpdateMgrsCallCompletedEventHandler UpdateMgrsCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMgrsCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMgrsCall(string user_id, string pass, string call_id, string status, string aciklama) {
            object[] results = this.Invoke("UpdateMgrsCall", new object[] {
                        user_id,
                        pass,
                        call_id,
                        status,
                        aciklama});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateMgrsCall(string user_id, string pass, string call_id, string status, string aciklama, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateMgrsCall", new object[] {
                        user_id,
                        pass,
                        call_id,
                        status,
                        aciklama}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpdateMgrsCall(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMgrsCallAsync(string user_id, string pass, string call_id, string status, string aciklama) {
            this.UpdateMgrsCallAsync(user_id, pass, call_id, status, aciklama, null);
        }
        
        /// <remarks/>
        public void UpdateMgrsCallAsync(string user_id, string pass, string call_id, string status, string aciklama, object userState) {
            if ((this.UpdateMgrsCallOperationCompleted == null)) {
                this.UpdateMgrsCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMgrsCallOperationCompleted);
            }
            this.InvokeAsync("UpdateMgrsCall", new object[] {
                        user_id,
                        pass,
                        call_id,
                        status,
                        aciklama}, this.UpdateMgrsCallOperationCompleted, userState);
        }
        
        private void OnUpdateMgrsCallOperationCompleted(object arg) {
            if ((this.UpdateMgrsCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMgrsCallCompleted(this, new UpdateMgrsCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void UpdateMgrsCallCompletedEventHandler(object sender, UpdateMgrsCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMgrsCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMgrsCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
