// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Chester2MigrosStatusMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chester2MigrosStatusMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201412241813174_Chester2MigrosStatusMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
