// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MissingPropertiesAndIndices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MissingPropertiesAndIndices));
        
        string IMigrationMetadata.Id
        {
            get { return "201410301328450_MissingPropertiesAndIndices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
