// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S2933:Make \"cookies\" \"readonly\".", Justification = "Legacy Code Baseline", Scope = "member", Target = "~F:WebApp.XeroxChester.cookies")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1500:Curly brackets for multi-line statements must not share line", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.Migrations.Configuration.Seed(WebApp.Models.SQLServerContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1120:Comments must contain text", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.Migrations.Configuration.Seed(WebApp.Models.SQLServerContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1011:Closing square bracket must be followed by a space.", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.Migrations.Configuration.Seed(WebApp.Models.SQLServerContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1012:Opening curly bracket must be preceded by a space.", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.Migrations.Configuration.Seed(WebApp.Models.SQLServerContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1500:Curly brackets for multi-line statements must not share line", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.Startup.Configuration(Owin.IAppBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1313:Parameter 'Migros_Cagri_No' must begin with lower-case letter", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.XeroxChester.Create(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.DateTime)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1313:Parameter 'Cagri_Durumu' must begin with lower-case letter", Justification = "Legacy Code Baseline", Scope = "member", Target = "~M:WebApp.XeroxChester.Update(System.String,System.String,System.String,System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1118:Add a \"protected\" constructor or the \"static\" keyword to the class declaration.", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.BundleConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.EmailService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1118:Add a \"protected\" constructor or the \"static\" keyword to the class declaration.", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.FilterConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.ApplicationDbContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.ExternalLoginListViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.ForgotPasswordViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.LoginViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.ManageUserViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.RegisterViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.Models.ResetPasswordViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "S1118:Add a \"protected\" constructor or the \"static\" keyword to the class declaration.", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.RouteConfig")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1402:File may only contain a single class", Justification = "Legacy Code Baseline", Scope = "type", Target = "~T:WebApp.SmsService")]
